### ISSUE TITLE
Chinese Localization

### ISSUE THREAD

**Issue by bakaxyf** [Towdium/JustEnoughCalculation#1]
喷
既然是中国人 来个汉化吧

**Comment by Towdium** [comment]
别急别急....新手还在熟悉中....

**Comment by 3TUSK** [comment]
I know how to do it, perhaps I can send a pull request for it today.

**Comment by 3TUSK** [comment]
I will consider about it today.

**Comment by Towdium** [comment]
@3TUSK 我已经搞定了喂！

**Comment by 3TUSK** [comment]
@Towdium I choose to go die

**Comment by Towdium** [comment]
@3TUSK 我接锅
