### ISSUE TITLE
Not able to find calculator

### ISSUE THREAD

**Issue by Ryahn** [Towdium/JustEnoughCalculation#10]
I am not sure if this is conflicting the calculator mod itself. When I do an NEI search, I am not able to find the calculator that JEC provides.

I am using this currently for 1.7.10

**Comment by Towdium** [comment]
Hi!
That seems to be a wierd problem and doesn't occur in my client.
I add it to Infinity Evolved Skyblock and tested along with botania, projectE and forgeEssentials in my dev environmrnt and I cannot reproduce such problem.

Can you test with only NEI and JEC to see whether this problem sitll happens?
Or did you disabled some pages in NEI causing it not able to be found?

**Comment by Ryahn** [comment]
I think might be Calculator mod itself but I am unsure. I can test it more when I am home tonight. 

NEI has not been modified at all. So it should work. 

I am testing this in Resonant Rise 3.

**Comment by Towdium** [comment]
By the way, just downloaded Resonant Rise 3 and tested. Still cannot reproduce this problem.

Maybe you can check your mod list to see if the mod is activated.

**Comment by Ryahn** [comment]
That was just weird. I just did a fresh install of the pack and its work XD

Thank for the patience. <3
