### ISSUE TITLE
Crash with Alt + Tab

### ISSUE THREAD

**Issue by Hurricaneforces** [Towdium/JustEnoughCalculation#100]
It just crashed my client after Alt+tab to Chrome
Modpack: Enigmatica 6
[crash-2021-10-21_13.59.25-client.txt](https://github.com/Towdium/JustEnoughCalculation/files/7386766/crash-2021-10-21_13.59.25-client.txt)
6

**Comment by Discreater** [comment]
Did it always crash, or just crash once?
