### ISSUE TITLE
crash with gt6

### ISSUE THREAD

**Issue by Pnc6lx** [Towdium/JustEnoughCalculation#101]
i use this mod with gregtech6 ,shift +? with any recipe, then game crashed

**Comment by Pnc6lx** [comment]
https://paste.ubuntu.com/p/xSmNCPKzWH/
here is crash report

**Comment by Discreater** [comment]
Thanks for report. I will fix it in several days.

**Comment by Discreater** [comment]
What version of GT6 did you use? I can't launch MC with only GT6. Or what modpack are you playing?

**Comment by Discreater** [comment]
Fixed in https://github.com/Towdium/JustEnoughCalculation/commit/90da8971ace72a7c2311c32116f6bf29c3b658c7.
1.7.10-3.8.2 already released.
