### ISSUE TITLE
Remove JEI as a dep so I can use Roughly Enough Items

### ISSUE THREAD

**Issue by aaronhowser1** [Towdium/JustEnoughCalculation#102]
REI supposedly works out of the box with everything that uses JEI, but JEC has JEI as a dependency so the game doesn't launch without it.

**Comment by Towdium** [comment]
Really? Have you tried if it works with REI?

**Comment by aaronhowser1** [comment]
Yes, REI does not have the JEI mod id, so forge stops loading and displays an error that JEI is missing.

**Comment by yzl210** [comment]
Official REI support is now added
