### ISSUE TITLE
crash when hovering over item from mod Rid

### ISSUE THREAD

**Issue by naseer-rehman** [Towdium/JustEnoughCalculation#103]
[Pastebin of crash report](https://pastebin.com/raw/0VfwuuAN)

I am playing FTB Oceanblock and there is an item called a "Quartz Cluster" from the mod "Rid" (as it says in the tooltip when I hover over the item in JEI). However, when I open the calculator interface and hover over this same item, my game immediately freezes, saves, and crashes, generating the report linked above.

**Comment by yzl210** [comment]
Fixed
