### ISSUE TITLE
1.18.2 crash on server launch

### ISSUE THREAD

**Issue by fabbe50** [Towdium/JustEnoughCalculation#113]
Dedicated server crashes on launch. Crash log attached.

[crash-2022-08-14_11.48.15-fml.txt](https://github.com/Towdium/JustEnoughCalculation/files/9333301/crash-2022-08-14_11.48.15-fml.txt)

**Comment by yzl210** [comment]
Fixed

**Comment by NielsPilgaard** [comment]
This also happens on 1.16.5, JustEnoughCalculation-1.16.5-3.9.0

**Comment by NielsPilgaard** [comment]
And JustEnoughCalculation-1.16.5-3.9.1 for that matter 😅

**Comment by yzl210** [comment]
> And JustEnoughCalculation-1.16.5-3.9.1 for that matter 😅

Please post the log

**Comment by NielsPilgaard** [comment]
The log looks a bit weird because it was running as a GitHub Action, but here it is:
https://gist.github.com/NielsPilgaard/1790e69db3dcbc972e9c3a3edbf7b965

Link to the action run:
https://github.com/EnigmaticaModpacks/Enigmatica6/runs/7956829834?check_suite_focus=true

**Comment by yzl210** [comment]
Nvm, I’ll fix for 1.16
