### ISSUE TITLE
Both calculators lack crafting recipes in the 1.18 latest version (jecalculation-forge-1.18.2-4.0.1.jar)

### ISSUE THREAD

**Issue by hiddenyak** [Towdium/JustEnoughCalculation#120]
Both items do not have recipes in JEI/REI in the latest forge version jecalculation-forge-1.18.2-4.0.1.jar

To reproduce:
1. Install jecalculation-forge-1.18.2-4.0.1.jar
2. Install JEI/REI
3. Press "R" on either calculator item to attempt to see crafting recipe

**Comment by yzl210** [comment]
Fixed in dev
