### ISSUE TITLE
I cant shift click a recipe in to the calculator 1.18.2

### ISSUE THREAD

**Issue by Furnaced** [Towdium/JustEnoughCalculation#122]
i put the mod in stoneblock 3 and doesnt work

**Comment by ekgame** [comment]
I don't think you're supposed to be able to do that. Normally you would click on an item in JEI and drag it into the calculator.

Was there a feature like that before?

**Comment by skupr** [comment]
I have issues with JEC in 1.18.2 too.
Modpack: Stoneblock 3, versino 1.2.1
JEC version: JustEnoughCalculation-1.18.2-3.9.0

I cannot add receipt into calculator from REI.
I've dragged desired item to calculator. Then in ingredients tab I click on the item:

![2022-11-14_09 13 28](https://user-images.githubusercontent.com/783636/201561083-39d88c9a-c3b8-4cbd-a0f2-ebc7824d7ab2.png)


Receipes list is opened, as it should be.
But the "+" button in the receipe is red and it says either "unable to move item to a 2x2 grid" or "not enough materials". It seems like it doesn't detect REI context or something, and behaves like in the normal user inventory.

![2022-11-14_09 05 10](https://user-images.githubusercontent.com/783636/201560709-1bd2f8aa-9e9e-438d-b902-c6edbc19b408.png)

Also, weird thing that I cannot go back from REI into calculator. I press Escape button - and it goes into inventory, not into calculator.

I still can add receipes manually by hand-picking all ingredients, though - but it's much longer, obviously.

Please please fix this 🙏

**Comment by yzl210** [comment]
3.9.0 isn't supposed to support this...
4.0.0+ added support for rei
