### ISSUE TITLE
[1.18.2] invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by ZornTaov** [Towdium/JustEnoughCalculation#124]
Got the error `Exception message: java.lang.RuntimeException: Attempted to load class me/towdium/jecalculation/events/GuiScreenEventHandler for invalid dist DEDICATED_SERVER` while trying to load the mod in a Stoneblock3 server.  This is because that event handler is being loaded on both client and server when it should only be client side.  I'm not exactly certain what the fix will be since you're doing a tri-release of the mod, but one fix would be `@Mod.EventBusSubscriber(modid = YourMod.MOD_ID, bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)` with value = Dist.CLIENT being the important field.

**Comment by yzl210** [comment]
I can't reproduce the issue, what version of jeca are you using and can you post the log?

**Comment by ZornTaov** [comment]
[2022-11-16-4.log](https://github.com/Towdium/JustEnoughCalculation/files/10071868/2022-11-16-4.log)
error starts on line 68, using stoneblock3 pack version 1.3.0 and jeca version 3.9.0

**Comment by yzl210** [comment]
This is why. It's fixed in 4.0.0+

**Comment by ZornTaov** [comment]
Gotcha.  It works if I have it just on my client though, so I'll wait for 4.0.0 to release on CurseForge.

**Comment by yzl210** [comment]
It's already released

**Comment by ZornTaov** [comment]
Oh, I'm dumb, I never pushed the "view all" button, didn't know there was an alpha build.  My bad, this can be closed.
