### ISSUE TITLE
Recipe Manager having problems with math/craft item recipe

### ISSUE THREAD

**Issue by MinesBoom** [Towdium/JustEnoughCalculation#125]
I am using "jecalculation-forge-1.18.2-4.0.1.jar" on a private Server and whenever i am reloading it (to add recipes with CraftTweaker), i saw two errors in the console:
"[ERROR] .... [minecraft/RecipeManager]: Parsing error loading recipe jecalculation:item_calculator_craft" followed by "com.google.gson.JsonSyntaxException: Unknown item 'forge:stone' "
and
"[ERROR] .... [minecraft/RecipeManager]: Parsing error loading recipe jecalculation:item_calculator_math" followed by "com.google.gson.JsonSyntaxException: Unknown item 'forge:ingots/iron' "

So i took a look into the recipe .jsons for both items and saw "item": "forge:ingots/iron"
as well as "item": "forge:stone" (last one only in the recipe for craft calculator)
My guess is, that it should be "tag" instead of "item", but i can be wrong.

Have a great day.

**Comment by yzl210** [comment]
Fixed in dev
