### ISSUE TITLE
Problem with machine crafting recipes calculation in GTNH (2.5.1) for Minecraft version 1.7.10

### ISSUE THREAD

**Issue by lao-pan** [Towdium/JustEnoughCalculation#144]
In the recent GTNH update 2.5.1, it's not possible to use machine crafting recipes. You can't use the "?" button to fetch crafting recipes from NEI (Not Enough Items) for machines; only basic vanilla recipes can be fetched. Sometimes, errors may also occur.
![image](https://github.com/Towdium/JustEnoughCalculation/assets/124324563/419ca5db-5050-4904-9e3d-3c572c15ca38)
![image](https://github.com/Towdium/JustEnoughCalculation/assets/124324563/342e5073-7ba4-43f1-b9d3-f606508fa3a2)

**Comment by SmileYik** [comment]
I have the same issue, i found that GT-Unofficial marked `Deprecated` at `GT_NEI_AssLineHandler` in last year(https://github.com/GTNewHorizons/GT5-Unofficial/blob/9a2741128a78bb52eba50a631126e090a5a2abd8/src/main/java/gregtech/nei/GT_NEI_AssLineHandler.java).
And this class is be deleted in current. 

So i think this code need to update:  https://github.com/Towdium/JustEnoughCalculation/blob/19fb4c49c32e53c8fa19a6bc79297de2a6876d93/src/main/java/me/towdium/jecalculation/nei/adapter/GregTech.java#L65C1-L65C1
I don't know where is the GT5 code move to, so in my opinion, just need predetection `getAssLine` not be null then to check recipe is its instsnce or not.

**Comment by Discreater** [comment]
Yeah, GTNH rafactored the recipeMap of the GT5. I'm trying to fix it.

**Comment by Discreater** [comment]
New version have been published to CurseForge and [Github releases](https://github.com/Towdium/JustEnoughCalculation/releases/tag/1.7.10-3.8.6)
