### ISSUE TITLE
REI不能直接转移配方

### ISSUE THREAD

**Issue by qrmd0** [Towdium/JustEnoughCalculation#150]
我为CABIN整合包安装JECa时发现不能一键添加配方，编辑配方只能靠手动一个一个地添加，希望能提供REI的一键转移支持。
REI版本：8.3.662
JECa版本：3.8.2

**Comment by yzl210** [comment]
4.0.0+添加了支持

**Comment by zTotto** [comment]
Can you do the same for 1.18? Thanks!
