### ISSUE TITLE
Rei "Move Items" function not working with REI

### ISSUE THREAD

**Issue by zTotto** [Towdium/JustEnoughCalculation#152]
Move items is not compatible it says "can't move to this inventory".

REI: 8.3.681
JEC: 3.9.0
MC: 1.18.2 Forge

**Comment by yzl210** [comment]
Use 4.0.0+

**Comment by zTotto** [comment]
My bad, it was marked as alpha on curseforge so I had to click on "show alpha files". Thank you!
