### ISSUE TITLE
ItemStack render with broken texture

### ISSUE THREAD

**Issue by Fokson** [Towdium/JustEnoughCalculation#16]
http://puu.sh/rcRht/3858ee9032.jpg

Every item from the mod 'CustomDrones' renders as the missing texture item, and fails to do much of anything within the calculator.

Minecraft 1.10.2
JEC 2.0.1
[CustomDrones 1.5.0](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2667694-customdrones-for-your-everyday-needs-went-official)

**Comment by Towdium** [comment]
Yep, this issue is known. Even the items added by early dev version of JEC have such problem. Actually this is most likely caused when the item is registered in an uncommon way and I spent several hours to fix it XD. I'm not sure why this happen, but I will try to fix it.
