### ISSUE TITLE
Crash when saving a recipe

### ISSUE THREAD

**Issue by Towdium** [Towdium/JustEnoughCalculation#18]
This issue is originally post by @DFliyerz in #15 . For management, I move it to here:

The game crashes when saving the recipe of  Calculator Plug from the Calculator mod. The crashreport is in [http://pastebin.com/Fak9399Q](http://pastebin.com/Fak9399Q)

Currently, I am not able to reproduce this issue. After commit c90f497b17380c3413551f6db7ae136a955aeeac, I added more descriptions for exceptions, so it might be helpful to locate the problem. Therefore, if you are using a version later than 2.0.3, just post the crashreport here, I will check it.

**Comment by Tsukiumy** [comment]
just to dont open a new issue just for this, but the new versions of jei(beta) will break if you try to add a new recipe to the calculator
here is the log if it can help when you update for the new version
https://gist.github.com/Tsukiumy/8e099f36b79f0c005adc331c06868470

**Comment by Towdium** [comment]
@Tsukiumy Got it, I'll look into it.

**Comment by Towdium** [comment]
Closing this issue since it's too far ago and cannot reproduce.
