### ISSUE TITLE
Crashed with JEI 1.10.2-3.13.2.353

### ISSUE THREAD

**Issue by number5** [Towdium/JustEnoughCalculation#21]
Here is the crash report, this happen when I adding a Botania lens recipe to JEC, I suspect JEI change a lot on their end.
[crash-2016-11-05_11.37.16-client.txt](https://github.com/Towdium/JustEnoughCalculation/files/572922/crash-2016-11-05_11.37.16-client.txt)

**Comment by Towdium** [comment]
Thanks for report!
Will look into it soon.

**Comment by Towdium** [comment]
Should be fixed in the latest release.
Do reopen this issue if it continues to crash.
