### ISSUE TITLE
suggestion for a new calculator

### ISSUE THREAD

**Issue by larskr96** [Towdium/JustEnoughCalculation#26]
hello, I have a suggestion and that is to add a mass calculator that calculates multiple things at once
that would be good if your making a build and you now what you want to make but dont now how much resurses it will take.
btw sorry for the bad english

**Comment by Towdium** [comment]
Thanks for the suggestion.
Umm, I guess I understand what you mean. I will keep it in the plan.
Let be give you a simple workaround. For example, you want to calculate 10 ladders and 20 torches. Then you can choose one item as a "label", for example, apple, and record a recipe that takes 10 ladders and 20 torches as input and one apple as output. Finally, calculate the cost for an apple, you should get what you want.

**Comment by Towdium** [comment]
Maybe you can give the new version a try. There is a workaround for such problems. Try to watch the update video for instructions on how to use. Any comments are welcomed.

**Comment by Towdium** [comment]
Since the label system is out for a while, I'm going to close this issue.
Open another issue for further discussion if any.
