### ISSUE TITLE
[1.10.2] Client start up crash: IllegalArgumentException 

### ISSUE THREAD

**Issue by DeadSix27** [Towdium/JustEnoughCalculation#29]
Foamfix: 0.6.0-beta3
Forge: 1.10.2-forge1.10.2-12.18.3.2221
JEC: JustEnoughCalculation-1.10.2-2.5.0.jar

Client crashes on startup, possible JustEnoughCalculation incompat.?

Posted this on both issue trackers, as I'm unsure which of both these mods causes this.

Other issue Link: https://github.com/asiekierka/FoamFix/issues/35

Stacktrace: http://pastebin.com/yTbmhzmL

**Comment by asiekierka** [comment]
A potential ~~solution~~ workaround would be to check if originalModel.getClass() has a "transforms" field - I know mine do, despite being a different class.

**Comment by Towdium** [comment]
Got it, will try to fix it.

**Comment by Towdium** [comment]
The change will be released soon. Do open another issue if it doesn't work.
