### ISSUE TITLE
[Suggestion] A way to calculate what machines are needed to craft an item, e.g. a Crafting Table, a Furnace and a Macerator

### ISSUE THREAD

**Issue by TheRandomLabs** [Towdium/JustEnoughCalculation#30]

**Comment by Towdium** [comment]
If I'm not misunderstanding, maybe you can try the button at bottom-right to switch the mode to catalyst? It should give you the machine if you use auto recipe transfer to write the recipes.

**Comment by Towdium** [comment]
Any update on this issue?

**Comment by TheRandomLabs** [comment]
Oh, sorry, I completely forgot about this issue. I'll check now.
EDIT: I tried putting in a Coal Plate from TechReborn, which requires a Compressor, and there was nothing in the Catalyst. It doesn't matter too much though, it was just a small suggestion.

**Comment by Towdium** [comment]
I will look into it. I think the machine should be transfered as catalyst if the mod follows JEI's interface, otherwise you can write the catalyst manually (it can be troublesome though).

**Comment by Towdium** [comment]
Closing this issue since it's too far ago. In 1.12, new API from JEI is used to provide support for catalysts, which should be really stable.
