### ISSUE TITLE
MAKE IT CLIENT SIDE!

### ISSUE THREAD

**Issue by Towdium** [Towdium/JustEnoughCalculation#33]
Going to work on that!

**Comment by sbrokalis** [comment]
Any ETA for that update, I really need that soon.

**Comment by Karrq** [comment]
Having this mod being clientside, much like BillOfMaterials is (for JEI) would be a WONDERFUL improvement! Imagine all the packs that currently lack this mod.... If the mod was clientside you could just add it to your loaded mods and be a happy player! If you need some help on the project I guess I could join you

**Comment by Towdium** [comment]
@LandKingdom Many thanks for your kindness. I'm getting back to work in hours. I will try to handle that myself, but I might find you for help if I fail to.

**Comment by Karrq** [comment]
Only problem would be that you can say I'm pretty new in minecraft modding, so I'll have to get the hang of it first and I'll probably need some explaining

**Comment by Towdium** [comment]
I'm closing this because it's implemented in 1.12 updates.
It is being tested on Discord: https://discord.gg/M3fNfTW.
