### ISSUE TITLE
[Suggestion] Add template items to use for calculating multi-block builds

### ISSUE THREAD

**Issue by Ceriwaen** [Towdium/JustEnoughCalculation#35]
Since many multi-block structures require blocks with different recipes it would be great if JEC added some empty items that we could use to figure out the resources needed for an entire structure.  An example is the Environmental Tech Solar Arrays: to determine if I have enough resources for the entire structure I added a recipe for cobblestone that took the inputs as all the required components.  If there were blank, recipe-less items added by JEC I wouldn't have to overwrite an item.

**Comment by Towdium** [comment]
Hi!

Have you checked [this video](https://www.youtube.com/watch?v=yRVedm5x3b4&t=52s)? ^_^

**Comment by Ceriwaen** [comment]
I had not!  That's perfect!
