### ISSUE TITLE
[Suggestion] Cross world support

### ISSUE THREAD

**Issue by pot-code** [Towdium/JustEnoughCalculation#36]
It's very annoying to add the same recipe over and over time when I switch the world. It would be very nice to reuse the same copy.

**Comment by Towdium** [comment]
Thanks for report!

It is very likely thare being such feature in the 1.12 version, which is still WIP. Users should be able to export and import records. That could solve this problem.

But for versions before 1.11, no more features will be added except for major bug fix. But there is an alternative solution! Simply go to the directory `%save_directory%/playerdata/%uuid%.jeca`, and all your records sould be in the file. All you need to do is copy the file to another world save.

Let me know if you have any problems.

**Comment by pot-code** [comment]
@Towdium 连文件名都一样，无痛复用了，works like a charm!

**Comment by Towdium** [comment]
惊了 突然中文
