### ISSUE TITLE
Only the Left Arrow works when flipping through groups while adding recipes

### ISSUE THREAD

**Issue by whizzball1** [Towdium/JustEnoughCalculation#37]
When adding a recipe and picking a recipe group for it, you can only press the left arrow. Not a horrible bug, but a bit problematic in its own way.

**Comment by Towdium** [comment]
Thanks for report!

Issue confirmed. I'm a little busy with minecraft 1.12, but I will try to have it fixed.

**Comment by Towdium** [comment]
Should have been fixed in last commit.
