### ISSUE TITLE
1.12.2

### ISSUE THREAD

**Issue by MineplayerHDYT** [Towdium/JustEnoughCalculation#38]
Please update this great mod to 1.12.2

**Comment by Towdium** [comment]
It's on the way. But since I'm in my last year of undergraduate study, I'm super busy. You can track the progress on curse page (or try build from source if you want).

**Comment by KAfable** [comment]
Hey sorry for the necropost, but also looking forward to a 1.12.2 release as I'm planning for a decent amount of microcrafting in my pack, and wanted to provide this tool as it's adds a powerful convenience factor. Good luck in your studies!

**Comment by uumas** [comment]
Any status update on this? Would love to see it happen!

**Comment by KindarConrath** [comment]
He has been working on it, last commit said that the search function was almost complete! And that was only a week ago. I too am excited to see this mod up and running on 1.12.

**Comment by Towdium** [comment]
I'm closing this because it's ready for testing for 1.12.
You are welcomed to join the discord server by https://discord.gg/M3fNfTW.
