### ISSUE TITLE
No Issue

### ISSUE THREAD

**Issue by MarikCZ** [Towdium/JustEnoughCalculation#39]
Really looking-forward 1.12 update! ;-) I really miss it... Can't wait for it... ;-)
Wish good luck in development of new update!

**Comment by KAfable** [comment]
Hey also wanted to chime in and saying that I'll be looking forward to a 1.12 version as well.

**Comment by MarikCZ** [comment]
I really must all the 4 emojies... 🗡 

Merry XMas and Happy New Year 2018!

**Comment by Towdium** [comment]
Merry XMas and Happy New Year to you guys too
Might get back to work if the following semester is not busy as hell ;)

**Comment by KindarConrath** [comment]
I'm going to assume that this semester was as busy as you suspected it to be. I'm hopeful that once summer break comes around you'll want to get back into modding!

**Comment by Towdium** [comment]
I'm closing this because it's ready for testing for 1.12.
You are welcomed to join the discord server by https://discord.gg/M3fNfTW.
