### ISSUE TITLE
New JEI Feature "Bookmark" don't work with "drag-and-drop"

### ISSUE THREAD

**Issue by ReiDaTecnologia** [Towdium/JustEnoughCalculation#49]
As the title say. JEI added a new feature (a really cool one tbf) that allow us to add items to the bookmark and it can be accessed anytime to see the use or recipe, but when you try to use it to drag-and-drop in the crafting calculator it don't work. It will be so cool if it works, will be really useful imo.
Great mod btw! :D
2Lazy2Calc :P

**Comment by Towdium** [comment]
Thanks for letting me know!

Form my current understanding, JEI do not have API for that at the moment. I have sent request for it. If you want, you can have a check of the issue https://github.com/mezz/JustEnoughItems/issues/1491. I am willing to add support for that when there is a conclusion.
