### ISSUE TITLE
Request: Add 1.9 Support

### ISSUE THREAD

**Issue by liftoff** [Towdium/JustEnoughCalculation#5]
Someone was bound to ask sooner or later :smile: 

Seriously, this mod is great.  Keep up the good work.

**Comment by Towdium** [comment]
It seems it's not too hard, but I'm kind of busy these days. I think I will finish the planed features bufore move to 1.9

**Comment by Towdium** [comment]
I will close it since the alpha version for 1.9 and 1.10 has been out!
Have fun :)
