### ISSUE TITLE
crash when import recipes

### ISSUE THREAD

**Issue by ZHENGLOC** [Towdium/JustEnoughCalculation#50]
mod version: JustEnoughCalculation-1.12.2-3.1.0
forge version: forge-1.12.2-14.23.5.2808-universal

crash reports：https://paste.ubuntu.com/p/FC2XvHqyY7/

**Comment by Towdium** [comment]
Thanks for report! Can you please try this one to see if it works?

[JustEnoughCalculation-1.12.2-3.1.1-pre1.zip](https://github.com/Towdium/JustEnoughCalculation/files/2846309/JustEnoughCalculation-1.12.2-3.1.1-pre1.zip)

**Comment by ZHENGLOC** [comment]
Yes, it can works now.

**Comment by Towdium** [comment]
Fixed in e87f2ade4266fa7a34baeff69edaa5bcd7821e14
