### ISSUE TITLE
"Internal Server Error" when trying to join with Aether Legacy

### ISSUE THREAD

**Issue by GAsplund** [Towdium/JustEnoughCalculation#51]
Server Log:
https://pastebin.com/zw12VsWD

**Comment by Towdium** [comment]
Thanks for report!

Can you please check if this build solves the issue?

[jecalculation-1.12.2-3.1.2.zip](https://github.com/Towdium/JustEnoughCalculation/files/2877416/jecalculation-1.12.2-3.1.2.zip)

**Comment by Towdium** [comment]
Should be fixed in 76eccf8575a7b3c3530fa2a6bf920e506ed5d590. Feel free to leave comments if it doesn't work for you.
