### ISSUE TITLE
Items sharing same oredicts merge wrongly when one of these item actually should be a exact one

### ISSUE THREAD

**Issue by AmberArr** [Towdium/JustEnoughCalculation#61]
Items sharing same oredicts merge wrongly when one of these item actually should be a exact one.

**Reproduction**:
I encounter it when playing with Pam's Harvestcraft. 

1. add this to recipe list
![1](https://user-images.githubusercontent.com/51911333/63905780-dc5bc000-ca47-11e9-8db2-514683eb677d.png)

2. nothing wrong
![2](https://user-images.githubusercontent.com/51911333/63905835-12993f80-ca48-11e9-97cb-d37f03807dbe.png)

3. the corn and "Ore: listAllVeggie" merge wrongly
![3](https://user-images.githubusercontent.com/51911333/63905568-36a85100-ca47-11e9-9fdd-1943c8040500.png)

**Version**:

- Minecraft 1.12.2
- Forge 14.23.5.2838
- JEI 4.15.0.268
- JEC 1.12.2-3.2.0

**Comment by Towdium** [comment]
Thanks for report!

I will check it soon.

**Comment by Towdium** [comment]
Should be fixed in latest release. Don't hesitate to find me again if it doesn't work.
