### ISSUE TITLE
Crafting 

### ISSUE THREAD

**Issue by ChubbyDuck** [Towdium/JustEnoughCalculation#66]
Maybe I'm missing something, but is there a way to access the "Steps", when you are already on a crafting table with all needed simple resources, or at least somehow to quickly find the item in JEI, so then I can upload it from JEI to a craft table? Because my flow currently is next: I gather all simple resources, and then go to steps and make items one by one, switching between calc and crafting table, and searching for complex items in JEI, which is not very convenient.

**Comment by Towdium** [comment]
The answer is no, but your situation makes sense to me. You might know that rendering overlays in Minecraft makes many troubles like overlapping contents or incorrect layouts, and the competition is getting worse recently. That's the reason I'm not making it.

But here's an alternative: you can first add items in steps tab into JEI bookmarks (you can pick items directly inside calculator GUI), then refer to items in bookmarks in crafting table. I know it's not a perfect solution, but I cannot come up with a better one without digging into some terrible conflicts.

**Comment by ChubbyDuck** [comment]
Thank you for the fast answer! Your suggestion actually solves the main issue - searching of complex items to craft, so I think nothing extra is needed, thanks a lot!

**Comment by ChubbyDuck** [comment]
I've just come up with one raw idea, on top of your suggestion. Not sure if it's possible, but maybe it'll help: 
What if JEI would have bookmark groups? (I'm not sure it doesn't, but I haven't found anything like that). So having that as an option in JEI, you can actually add an option to calc to create such groups from the steps, naming them by the name of the main recipe (if the groups would be nameable).

**Comment by Towdium** [comment]
As far as I know, JEI doesn't have such things. It doesn't sound intuitive for JEI to have such feature.

**Comment by Towdium** [comment]
I'm closing this issue since there seems nothing I can do to help.
