### ISSUE TITLE
[Feature Request/Suggestion] Displaying required item count as stacks

### ISSUE THREAD

**Issue by ghost** [Towdium/JustEnoughCalculation#69]
I'm currently making a thermal evaporation thing from Mekanism, the max size seems to require about 240 thermal evaporation blocks and 4 advanced solar panels, so I've added that to a recipe (just using a nether star as an end result as a place holder)

![javaw_6sh3DAC3Kj](https://user-images.githubusercontent.com/63269417/89203315-4d86ea00-d5ac-11ea-905e-2172d3d4fbb5.png)
As you can see, things like this commonly go above 64 items, so I have to take that number figure out how many stacks it is. Obviously, it isn't all that difficult to do so... but being able to simply toggle something and having it shown something like:

(IronIngotImage represents the iron ingot icon)

'IronIngotImage
64x6 + 15'

would be a lot nicer, considering I have to do this very frequently.

I wouldn't mind if the value text is literally '"64x" + numOfStacks + " + " + remainder', but if you want to make it nicer, feel free.

**Comment by Towdium** [comment]
Does it works for you if it shows in tooltip?

**Comment by ghost** [comment]
In the tooltip? similar to the copy/paste tool from building gadgets? If so, that'd be fine too!

**Comment by Towdium** [comment]
Implemented in 3.6.2. Since 1.12 is quite old version, it will not get ported back.
