### ISSUE TITLE
Recipes that need over 14 unique items can't be calculated

### ISSUE THREAD

**Issue by aaronhowser1** [Towdium/JustEnoughCalculation#70]
![image](https://user-images.githubusercontent.com/15698722/90309727-a27e0680-deb0-11ea-9276-5af3cc59964d.png)
![](https://cdn.discordapp.com/attachments/166630061217153024/744126489418792960/unknown.png)

This is using JustEnoughCalculation-1.12.2-3.2.3

**Comment by KindarConrath** [comment]
while it's not ideal, you could do this by breaking the recipe up into multiple smaller recipes using labels and then have the final item made of all the label groups

**Comment by aaronhowser1** [comment]
Is there a way to do this through the JEI integration, or would I have to write down all the items and split them up?

**Comment by Towdium** [comment]
@aaronhowser1 You can have as many ingredients in 1.14+, I guess. But in earlier versions, which are not in development, I'm sorry you can only achieve it manually. It truely bothered me sometimes, but I have no time for it.

**Comment by aaronhowser1** [comment]
It's totally fine, placeholders work instead
![image](https://user-images.githubusercontent.com/15698722/90988922-280e5000-e55c-11ea-89c6-0c3e55a39bda.png)

**Comment by Towdium** [comment]
@aaronhowser1 Nice! You got the point!
