### ISSUE TITLE
[Suggestion] Feature to pin recipes on first person screen and track player's inventory, as quests.

### ISSUE THREAD

**Issue by ChromaPIE** [Towdium/JustEnoughCalculation#72]
Like, when I successfully wrote a recipe i am able to pin it on the screen and keep myself advised how many and what items to be collected, when the calculator is in the inventory. Just like the quests waiting to be done, so i am able to focus on working among machines instead of having to open and close the calculator gui again and again.

btw i am a fan using 1.12.2 version of JEC. Hope you are still maintaining the 1.12.2 version. Appreciate that.

**Comment by KatoNamus** [comment]
This would be brilliant. Yes, please.
[TheBOMPlugin](https://www.curseforge.com/minecraft/mc-mods/thebomplugin) used to by my go-to mod for that, but to actually have a Bill Of Materials function in JEC for MC 1.15+ would be a true game changer... er... pardon the pun.

**Comment by Towdium** [comment]
So how do you expect to be? Like an overlay in game screen? It's not too hard to do, but you know competion for screen space is there for a long time, this can lead to many compatibility issues. In #66 I have had some discussions and workarounds for the issue. @ChromaPIE mentioned quests, I agree with that. But you can see no "quest mod" is actually doing an overlay for quests. Also, if looking for the item takes too much time for you, I suggest using client mode and bind the GUI to keyboard.

But there are some other things I can do to help, which seems quite good to me: I can add some integration to JEI bookmark or simply JEI overlay, by adding the cost list to item tooltip (or triggreed with key binding like shift). Then you can have something quite close to TheBOMPlugin. The cost list can be very long, so I need to further think about the presentation.

By sorry, I only update 1.12 if there are severe bugs, new features will not be added.

**Comment by KatoNamus** [comment]
Hmm... good point. Personally, I'd prefer a customizable (size, location, orientation (vertical or horizontal icons)) element that I could manually put exactly where I want. [RPG-HUD](https://www.curseforge.com/minecraft/mc-mods/rpg-hud) being my inspiration here, of course.
Other options to consider would be just to update the user with text notifications, e.g. picking up a cobblestone (which my recipe needs 256 of) would show either in chat or some other text notification "Cobblestone: 4/256" and if I take a stack from a chest it would update as "Cobblestone: 68/256". Maybe have it on a bit of a delay so it doesn't spam you if you're mining, just updates when you've stopped receiving that item for ten seconds or so.

**Comment by t0suj4** [comment]
I feel like this could be added as a mod.

**Comment by TheMusicMeister** [comment]
Sorry for the necro post but -

I had thought about trying to write a mod or plugin to this effect, but in looking through the JEC code I wasn't really able to locate where I would need to bind into in order to retrieve the materials list and recipe sequence.  If someone could point me in the right direction of where to look then I'd be willing to try my hand at something like this.

**Comment by ekgame** [comment]
There's a fairly similar feature in the works: https://github.com/Towdium/JustEnoughCalculation/pull/98. It needs a bit more improvement, but you can download a the mod with it from the discord server linked in the readme.

**Comment by ekgame** [comment]
@TheMusicMeister

**Comment by Towdium** [comment]
Since we have calculator widget now, I'm closing this issue. Check #98
