### ISSUE TITLE
Recipe output amount getting reset to 1

### ISSUE THREAD

**Issue by putterybopcorn** [Towdium/JustEnoughCalculation#73]
I am having a bug where my recipe output quantities will all get set to 1. No idea what is causing it. Have tried with client mode true and false, happens either way. Does not seem to be affecting liquid recipes (the liquid output is not set to 1mb). Also I am on  1.12.2-3.2.3

**Comment by Towdium** [comment]
Does it still happen if you create a new world?

**Comment by draeath** [comment]
I can replicate this as well. (omnifactory pack, 1.12.2-3.2.3)

It seems to trigger when I have a large number of recipes added. If you remove all recipes and "start fresh" (no new world required) it fixes it, until some time again later once you have many recipes added again.

**Comment by draeath** [comment]
It might be coincidental, but after upgrading to 1.12.2-3.2.4 and loading my save, the recipes that were showing the incorrect output amounts are corrected.

It could be that the issue requires some amount of runtime duration or such to trigger and that restarting the game clears it temporarily. I'll try to follow up if I notice it continuing.

@putterybopcorn it would be useful if you were to try updating as well. It should be safe to just replace the `JustEnoughCalculation-1.12.2-3.2.3.jar` in your game with [JustEnoughCalculation-1.12.2-3.2.4.jar](https://www.curseforge.com/minecraft/mc-mods/just-enough-calculation/files/3056137) and see if the issue persists for you.

**Comment by Towdium** [comment]
Is there any clue that this issue is related to Mekanism? 3.2.4 only adds some safety check mainly related to Mekanism-related recipes.

**Comment by draeath** [comment]
The pack I use does not have mekanism.

I have yet to notice the problem again. Hopefully that's a coincidence, because if this is a race condition... lol

**Comment by mkaito** [comment]
This is still a thing on 1.12.2-3.2.4 -- in Omnifactory dev snapshot.

**Comment by Towdium** [comment]
Can anyone with this issue provide export of his recipes, within a modpack public available, so that I can try it? And also, are all of you having issue with Omnifactory only? To be honest, I haven't play minecraft for months, sorry.

Guess I need to give Omnifactory a try.

**Comment by tominator1pl** [comment]
It's not just the Omnifactory. I tested it a bit and it happens with items with the same ID. I tested it with only JEI_1.12.2-4.16.1.301 and JustEnoughCalculation-1.12.2-3.2.5 installed on a brand new world with just one recipe for dye since they use the same IDs and it still happens. I think it might have to do with suggestions that can display since adding a recipe for another dye so it doesn't diplay suggestions fixes it. Here's a short video I made so you can replicate it: https://youtu.be/7tsOLU0C7Y0

**Comment by Towdium** [comment]
@tominator1pl Great! You are my hero!
