### ISSUE TITLE
UX: Delete button has misleading image

### ISSUE THREAD

**Issue by t0suj4** [Towdium/JustEnoughCalculation#74]
- Delete button should be a Trash can.
- Cancel button should be a Red Cross - no action, close ui element. In JEC case, close popup like the one with buttons Edit Recipe, Delete Recipe.

The expected behaviour of a Red Cross button is cancel/close.

I use version 1.12.2-3.2.3

**Comment by yzl210** [comment]
Fixed in 8aebdca
