### ISSUE TITLE
Crash report: JEC Causes a crash when attempting to save a recipe.

### ISSUE THREAD

**Issue by Nebby1999** [Towdium/JustEnoughCalculation#78]
Currently i'm building a modpack and i've noticed while playtesting that the JEC Resource calculator is crashing the game.

What i expect to happen: put an item on the calculator, search it's recipe, click the plus icon, save, show up the resources i need
What happens: I put the item, search the recipe, click the plus icon, the game crashes.
I've managed to reproduce this bug in both my heavily modded modpack (over 100 mods) and an almost fresh installation, with only JEC and JEI installed

Current MC Version: 1.16.5
Forge Versions: 
     Heavily modded: 36.0.14
     Fresh Installation: 36.0.21
JEC Version: 1.16.4-3.6.3
JEI Version: 1.16.4-7.6.1.70

Below i've attached two logs with said Crashes, the first one is from the fresh install with only JEI and JEC, and the second one is the heavily modded setup
[Fresh Install Log.log](https://github.com/Towdium/JustEnoughCalculation/files/5955058/Fresh.Install.Log.log)
[Heavily Modded Log.log](https://github.com/Towdium/JustEnoughCalculation/files/5955059/Heavily.Modded.Log.log)

I'd love to see this fixed ASAP, since it's a great mod and very useful, i can confirm that the problem might have arisen with the 1.16.5 update, because before in 1.16.4 i had no crashes whatsoever.

**Comment by Towdium** [comment]
It seems like JEI's '+' feature is broken in this version. I guess we need to wait for upstream fix for this issue.

**Comment by Nebby1999** [comment]
> It seems like JEI's '+' feature is broken in this version. I guess we need to wait for upstream fix for this issue.

youre saying that the problem arises from JEI and not JEC?

**Comment by Nebby1999** [comment]
> It seems like JEI's '+' feature is broken in this version. I guess we need to wait for upstream fix for this issue.

just noticed a new version of JEI, it seems to fix the issue

**Comment by Towdium** [comment]
Is there any related issues to be fixed? Or is it fine to close the issue?

**Comment by Nebby1999** [comment]
yup, the new version of JEI fixed the issue, i'll close this issue with this comment.
