### ISSUE TITLE
Using mousewheel in the help interfaces causes crash

### ISSUE THREAD

**Issue by qrmd0** [Towdium/JustEnoughCalculation#79]
version:1.12.2-3.2.5
it occurs in help interfaces that have only one page like these.
![Bug页1](https://user-images.githubusercontent.com/42112031/112417363-6b36d880-8d62-11eb-8efa-74a4a58f4cba.png)
![Bug页2](https://user-images.githubusercontent.com/42112031/112417365-6e31c900-8d62-11eb-8189-ae1c1148c4e0.png)
![Bug页3](https://user-images.githubusercontent.com/42112031/112417367-6eca5f80-8d62-11eb-9786-a256da184fca.png)

**Comment by Towdium** [comment]
Got it, thanks
