### ISSUE TITLE
Request of permission to repost JustEnoughCalculation on mcmod.cn

### ISSUE THREAD

**Issue by qrmd0** [Towdium/JustEnoughCalculation#81]
Can you give me permission to repost your Mod JustEnoughCalculation to ([MC百科](www.mcmod.cn)),which can let more Chinese players benefit from your Mod?And you can see this post A Web Site----Minecraft Mod Wikipedia(MCMOD.cn).

**Comment by Towdium** [comment]
Sure! Thanks.
