### ISSUE TITLE
Button tooltips have a delay before they show up

### ISSUE THREAD

**Issue by aaronhowser1** [Towdium/JustEnoughCalculation#82]
https://user-images.githubusercontent.com/15698722/116241400-7b0f5700-a72a-11eb-8673-e8542ec93ff1.mp4

`JustEnoughCalculation-1.16.5-3.6.4`

**Comment by Towdium** [comment]
I'm not sure if it bothers you, but this is intended. It's annoying to me if the tooltips keeps show up. I believe you wont need the tooltips few days later.
