### ISSUE TITLE
1.7.10 in GTNH 2.1.1.0 not working

### ISSUE THREAD

**Issue by kasper-tfg** [Towdium/JustEnoughCalculation#86]
Using 1.7.10 version 3.0.6.2 in the GTNH version 2.1.10 mod pack clicking the question mark button on a recipe display does not lead to bringing up the add recipe GUI, it simply does nothing.  The only way to add recipes is to manually create a new recipe and all the components one by one.

**Comment by Discreater** [comment]
`shift`+click
