### ISSUE TITLE
Game crash when using Industrial Foregoing recipes

### ISSUE THREAD

**Issue by NielsPilgaard** [Towdium/JustEnoughCalculation#89]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2658

> Trying to add an Industrial Foregoing recipe, possibly with fluid (in this case Latex), when using the Just Enough Calculations calculator can cause the game to crash ("Saving World" and exiting). In my case it was looking up Efficiency Addon +2 and Simple Machine Frame.

Crash report: https://pastebin.com/ENjUsN6E

### Versions
- Forge-1.16.5-36.1.31
- JustEnoughCalculation-1.16.5-3.7.1

**Comment by Towdium** [comment]
Thans for report, I'll check it
