### ISSUE TITLE
JEC, causes ProjectE to loose approx 4000 EMC values from modded items when ForgeEssentials is installed

### ISSUE THREAD

**Issue by SteelShot** [Towdium/JustEnoughCalculation#9]
Literally what title says,

ProjectE for some reason looses a major amount of EMC values from various mods, when JEC is installed along side ForgeEssentials.

Removing JEC everything works fine PE+FE work perfectly fine. I am not sure where the problem lies but the issue is there.
Referencing all issues made for your information

https://github.com/sinkillerj/ProjectE/issues/1230
https://github.com/ForgeEssentials/ForgeEssentials/issues/2075

**Comment by Towdium** [comment]
I need to confirm this bug is caused by me and I'm sorry for any convenience I have caused.
I have successfully located the problem. It should be solved soon.
Thanks for reporting it to me

**Comment by MaPePeR** [comment]
Can you elaborate on what is causing the issue? It is really weird.

**Comment by Towdium** [comment]
@MaPePeR I did some reflection to make black dye in botania able to be used as an ingredient in the recipe. I get the item for dye from registry and forget to check the result. So I added an itemstack with a null item into the recipe. I think this will heppen whenever an itemstack with null item is used.

**Comment by SteelShot** [comment]
The latest update seems to have fixed the issue, i can see lots of pages with items when i search "EMC:" in NEI.

**Comment by Towdium** [comment]
Oh, that is really a good news to me :)
