### ISSUE TITLE
Crash on Click to open JEI recipe in Crafting Calculator

### ISSUE THREAD

**Issue by KatoNamus** [Towdium/JustEnoughCalculation#90]
Hi Towdium, I just got a crash when I clicked on an item in the crafting calculator to open it's JEI recipe. Crashlog here: [Auto-uploaded by Not Enough Crashes](https://gist.githubusercontent.com/natanfudge/acd5a1358beacefe0246fa09001bc754/raw/89d106d3b3bacf3f2aa05771cd0d5328f874e2ca/crash.txt)

**Comment by Towdium** [comment]
My bad, the latest version is full of bugs.
