### ISSUE TITLE
JEC Crashes when using

### ISSUE THREAD

**Issue by DaniellePashayan** [Towdium/JustEnoughCalculation#92]
[crash-2021-07-30_13.51.46-client.txt](https://github.com/Towdium/JustEnoughCalculation/files/6909267/crash-2021-07-30_13.51.46-client.txt)
[crash-2021-07-30_13.44.49-client.txt](https://github.com/Towdium/JustEnoughCalculation/files/6909268/crash-2021-07-30_13.44.49-client.txt)

**Comment by Discreater** [comment]
Try the latest version(1.16.5-3.8.2): https://www.curseforge.com/minecraft/mc-mods/just-enough-calculation/files/3400535
