### ISSUE TITLE
Pressing "e" when in a text entry box closes the menu

### ISSUE THREAD

**Issue by EpicPuppy613** [Towdium/JustEnoughCalculation#93]
After opening the calculator, pressing the inventory button will close the menu no matter what, even if you are trying to enter text (search or jei) and the word you are entering has "e" in it.

MC Version: 1.16.5
Mod Version: 3.8.2
Forge Version: 36.2.0

**Comment by KatoNamus** [comment]
Ah, so it is this mod. I was trying to figure out what was causing it, assuming that it was just happening in JEC "as well". Anyhow, +1 here.
