### ISSUE TITLE
Crash with Immersive Engineering recipe

### ISSUE THREAD

**Issue by IC-Dyllac** [Towdium/JustEnoughCalculation#94]
Minecraft Version : 1.12.2
Forge Version: 14.23.5.2855 (Latest when submitting this report)

# Issue:
When adding a recipe that involves the Arc Furnace through JEI that **DOESN'T** have a slag output, game crashes.

# Mods:
- JustEnoughCalculation 1.12.2 - 3.2.6
- JustEnoughItems 1.12.2 - 4.16.1.301
- Immersive Engineering - 0.12 - 98

# Steps to reproduce:

1. Open crafting calculator and search on JEI an item that involves the Arc Furnace (ex. Iron ingot from iron grit)
2. Press the "+" to "Move Items" on a recipe that doesn't have a slag output (ex. Iron ingot from iron grit)
3. Crashes with exception "IllegalArgumentException: Stack can not be invalid!"

Image related:
![ErrorShow](https://user-images.githubusercontent.com/56610544/128770673-1c8cd285-4091-4c8c-88fd-c76ce76451cb.jpg)

I'm attatching the crash Log hoping it helps:
[crash-2021-08-09_14.39.54-client.txt](https://github.com/Towdium/JustEnoughCalculation/files/6957180/crash-2021-08-09_14.39.54-client.txt)

**Comment by Towdium** [comment]
Thanks for report
I'll have it fixed soon
