### ISSUE TITLE
Pressing "e" when in JEI text entry box closes the menu

### ISSUE THREAD

**Issue by progheal** [Towdium/JustEnoughCalculation#95]
Same as #93, but only happens in JEI text entry box. (It is fixed in JEC interface text entry box.)

Version info:
 - Minecraft: 1.16.5
 - Modpack: Seaopolis 6.0
   - Forge Version: 36.2.2
   - JEC Version: 3.8.3
   - JEI Version: 7.7.1.116

**Comment by Towdium** [comment]
emmmmmmmmm...
