### ISSUE TITLE
Recipes get erased frequently when switching from multiplayer to singleplayer and cannot re-import recipes.

### ISSUE THREAD

**Issue by jeffgamecube3** [Towdium/JustEnoughCalculation#97]
Froge version: release 1.7.10-Forge10.13.4.1614-1.7.10
Mod version: JustEnoughCalculation-1.7.10-3.8.0
NEI version: NotEnoughItems-1.7.10-1.0.5.120-universal
Playing on FTB Infinity Evolved 3.1.0

I am switching from multiplayer and singleplayer from time to time, mainly to test things. If I add recipes to the mod and switch from multiplayer to singleplayer, or the other way around, without closing the client, my recipes stay loaded, and I can use them in both instances. If I close my client and some back another day, the recipes are gone. It seems to only happen if I switch from multi to single AND if I close the client.

I also can export my recipes, I can see the file "group.json" has the recipes I have entered in-game, but I can't import them back, I only get a blank list in the import screen.

The recipes also stay in the "record.json" even if they don't appear in-game.

I love the mod so much, it's so useful for modpack with a lot of recipes and ingerdients, but I find it annoying that this bug occurs.

**Comment by Discreater** [comment]
It sounds strange.

> If I close my client and some back another day, the recipes are gone.

The first thing to check is, are you using the same client that you opened later? Did all the recipes disappear?

I have tested for some simple recipes in FTB Infinity Evolved 3.1.0. And I can export and import the recipes. Can you provide your `group.json` and `record.json`?

**Comment by jeffgamecube3** [comment]
I only use the official Minecraft launcher to launch modpacks, and each installation is in a seperate folder, so that shouldn't be the problem (although I know it could be one, just not in my case).

currently, the recipes i entered last time I played are still there, and I haven't logged in singleplayer since those recipes.

[data.zip](https://github.com/Towdium/JustEnoughCalculation/files/7022931/data.zip)
Here are both the files, and I still cannot import group.json in the mod's GUI.

**Comment by jeffgamecube3** [comment]
I was able to export and immediatly re-import my recipes (by creating a new groups.json) but I am unable to import the one I created last time (I checked the spelling, and renamed the file to groups.json).
[groups - new.zip](https://github.com/Towdium/JustEnoughCalculation/files/7022957/groups.-.new.zip)
This is the one I was able to re-import, the first one is the one I can't import.

**Comment by Discreater** [comment]
Fixed. That was caused by the unmatched JSON writer and reader. I will upload new version (3.8.1) to the CF.

**Comment by Discreater** [comment]
I'm sorry that you may need to re-add recipes.
